paths:
  data_dir: /data/scratch/john.pill/DATA/temp_humidity_index
  download_dir: /data/scratch/john.pill/DATA/temp_humidity_index/downloads
  charts_dir: /data/scratch/john.pill/DATA/temp_humidity_index/charts
  web_dir: /home/users/john.pill/public_html/temp-humidity-index

files:
  raw_grib: ifs_2t_dp_msl.grib
  raw_nc: ifs_2t_dp_msl.nc
  wet_bulb_nc: ifs_2t_dp_msl_tw_fast.nc
  thi_nc: ifs_thi.nc

retrieval:
  parameters: ['2d', '2t', 'msl']
  forecast_hours: 168
  step_increment: 6
