paths:
  data_dir: /Users/johnpill/DATA/temp_humidity_index
  download_dir: /Users/johnpill/DATA/temp_humidity_index/downloads
  charts_dir: /Users/johnpill/DATA/temp_humidity_index/charts

files:
  raw_grib: ifs_2t_dp_msl.grib
  raw_nc: ifs_2t_dp_msl.nc
  wet_bulb_nc: ifs_2t_dp_msl_tw_fast.nc
  thi_nc: ifs_thi.nc
