# Rename file to settings.yaml and update paths to your local environment.

paths:
  data_dir: path/to/data
  download_dir:  path/to/data
  charts_dir:  path/to/data/charts
  web_dir:  path/to/data/web

files:
  raw_grib: ifs_2t_dp_msl.grib
  raw_nc: ifs_2t_dp_msl.nc
  wet_bulb_nc: ifs_2t_dp_msl_tw_fast.nc
  thi_nc: ifs_thi.nc

retrieval:
  parameters: ['2d', '2t', 'msl']
  forecast_hours: 168
  step_increment: 6
